FROM node:alpine as build
USER node
WORKDIR /home/node
COPY package.json .
RUN npm install
COPY --chown=node:node . .
RUN [ "npm", "run", "build" ]

FROM nginx:latest
COPY --from=build /home/node/build /usr/share/nginx/html
EXPOSE 80
