version: '3.9'
services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./client
        target: /home/node
      - type: volume
        target: /home/node/node_modules
  api:
    build:
      context: ./api
      # identique en dev ou prod
      dockerfile: Dockerfile.dev
    # api écoute sur 80, et reverse proxy écoutera 80 donc on part sur 3001
    ports:
      - 3001:80
    volumes:
      - type: bind
        source: ./api/src
        target: /app/src
  db:
    image: mongo
    # on donnera un volume différent en fonction du dev ou prod
    volumes:
      - type: volume
        source: dbtest
        # endroit où c'est stocké sur image mongo
        target: /data/db
  reverse-proxy:
    build: 
      context: ./reverse-proxy
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    depends_on:
      - api
      - db
volumes:
  # laisse à mongo la possibilité de créer le volume
  dbtest: 